<?php
return [
	'icons' => [
		'1' => '../../../../Adventskalender/Resources/Public/Images/Bauble.png',
		'2' => '../../../../Adventskalender/Resources/Public/Images/Dove.png',
		'3' => '../../../../Adventskalender/Resources/Public/Images/Tree.png',
		'4' => '../../../../Adventskalender/Resources/Public/Images/Bow.png',
		'5' => '../../../../Adventskalender/Resources/Public/Images/Bells.png',
		'6' => '../../../../Adventskalender/Resources/Public/Images/Present.png',
		'7' => '../../../../Adventskalender/Resources/Public/Images/Candles.png',
		'8' => '../../../../Adventskalender/Resources/Public/Images/CandyCane.png',
		'9' => '../../../../Adventskalender/Resources/Public/Images/Stocking.png',
		'10' => '../../../../Adventskalender/Resources/Public/Images/Wreath.png',
		'11' => '../../../../Adventskalender/Resources/Public/Images/Angel.png',
		'12' => '../../../../Adventskalender/Resources/Public/Images/Snowman.png',
		'13' => '../../../../Adventskalender/Resources/Public/Images/Santa.png',
		'14' => '../../../../Adventskalender/Resources/Public/Images/GingerbreadMan.png',
		'15' => '../../../../Adventskalender/Resources/Public/Images/Rudolph.png',
		'16' => '../../../../Adventskalender/Resources/Public/Images/Teddy.png',
		'17' => '../../../../Adventskalender/Resources/Public/Images/Snowflake.png',
		'18' => '../../../../Adventskalender/Resources/Public/Images/SmallStar.png',
        '19' => '../../../../Adventskalender/Resources/Public/Images/Heart.png',
		'20' => '../../../../Adventskalender/Resources/Public/Images/Present2.png',
		'21' => '../../../../Adventskalender/Resources/Public/Images/Bauble2.png',
		'22' => '../../../../Adventskalender/Resources/Public/Images/Bell.png',
		'23' => '../../../../Adventskalender/Resources/Public/Images/Girl.png',
		'24' => '../../../../Adventskalender/Resources/Public/Images/Marbles.png',
		'25' => '../../../../Adventskalender/Resources/Public/Images/Star.png'
	],
	'closedWindows' => [
		'1' => '../../../../Adventskalender/Resources/Public/Images/Window1.png',
		'2' => '../../../../Adventskalender/Resources/Public/Images/Window2.png',
		'3' => '../../../../Adventskalender/Resources/Public/Images/Window3.png',
		'4' => '../../../../Adventskalender/Resources/Public/Images/Window4.png',
		'5' => '../../../../Adventskalender/Resources/Public/Images/Window5.png',
		'6' => '../../../../Adventskalender/Resources/Public/Images/Window6.png',
		'7' => '../../../../Adventskalender/Resources/Public/Images/Window7.png',
		'8' => '../../../../Adventskalender/Resources/Public/Images/Window8.png',
		'9' => '../../../../Adventskalender/Resources/Public/Images/Window9.png',
		'10' => '../../../../Adventskalender/Resources/Public/Images/Window10.png',
		'11' => '../../../../Adventskalender/Resources/Public/Images/Window11.png',
		'12' => '../../../../Adventskalender/Resources/Public/Images/Window12.png',
		'13' => '../../../../Adventskalender/Resources/Public/Images/Window13.png',
		'14' => '../../../../Adventskalender/Resources/Public/Images/Window14.png',
		'15' => '../../../../Adventskalender/Resources/Public/Images/Window15.png',
		'16' => '../../../../Adventskalender/Resources/Public/Images/Window16.png',
		'17' => '../../../../Adventskalender/Resources/Public/Images/Window17.png',
		'18' => '../../../../Adventskalender/Resources/Public/Images/Window18.png',
		'19' => '../../../../Adventskalender/Resources/Public/Images/Window19.png',
		'20' => '../../../../Adventskalender/Resources/Public/Images/Window20.png',
		'21' => '../../../../Adventskalender/Resources/Public/Images/Window21.png',
		'22' => '../../../../Adventskalender/Resources/Public/Images/Window22.png',
		'23' => '../../../../Adventskalender/Resources/Public/Images/Window23.png',
		'24' => '../../../../Adventskalender/Resources/Public/Images/Window24.png',
		'25' => '../../../../Adventskalender/Resources/Public/Images/Window25.png'
	]
];
